import os
templates_dir = os.path.join(os.path.dirname(__file__), 'web', 'templates')

lines = []
lines.append('{% extends "base.html" %}')
lines.append('{% block title %}Denetim Kaydi - Aether{% endblock %}')
lines.append('{% block page_title %}DENETİM KAYDI{% endblock %}')
lines.append('{% block content %}')
lines.append('<style>')
lines.append('.filter-bar{display:flex;gap:10px;flex-wrap:wrap;margin-ботtom:15px;align-items:center;}')
lines.append('.filter-bar input,.filter-bar select{padding:9px 13px;background:#0a0a0a;border:2px solid rgba(220,20,60,0.3);border-radius:8px;color:#eee;font-size:13px;}')
lines.append('.filter-bar input:focus,.filter-bar select:focus{outline:none;border-color:#dc143c;}')
lines.append('.filter-bar input{flex:1;min-width:180px;}')
lines.append('.cat-btn{padding:7px 13px;border-radius:20px;border:2px solid rgba(220,20,60,0.3);background:transparent;color:#aaa;cursor:pointer;font-size:11px;font-weight:700;transition:all 0.2s;white-space:nowrap;}')
lines.append('.cat-btn.active,.cat-btn:hover{border-color:#dc143c;color:white;background:rgba(220,20,60,0.2);}')
lines.append('.ev-row{display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.05);border-radius:10px;padding:10px 14px;transition:all 0.2s;}')
lines.append('.ev-row:hover{background:rgba(220,20,60,0.07);border-color:rgba(220,20,60,0.2);}')
lines.append('.ev-icon{font-size:18px;width:28px;text-align:center;flex-shrink:0;}')
lines.append('.ev-cat{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:1px;padding:2px 7px;border-radius:8px;flex-shrink:0;min-width:72px;text-align:center;}')
lines.append('.ev-action{color:white;font-weight:600;font-size:13px;flex-shrink:0;min-width:140px;}')
lines.append('.ev-detail{color:#666;font-size:12px;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}')
lines.append('.ev-time{color:#444;font-size:11px;flex-shrink:0;min-width:100px;text-align:right;}')
lines.append('.ev-btn{background:rgba(220,20,60,0.15);border:1px solid rgba(220,20,60,0.3);color:#dc143c;padding:4px 10px;border-radius:6px;cursor:pointer;font-size:11px;flex-shrink:0;transition:all 0.2s;}')
lines.append('.ev-btn:hover{background:rgba(220,20,60,0.3);}')
lines.append('.stats-bar{display:flex;gap:8px;flex-wrap:wrap;margin-ботtom:15px;}')
lines.append('.stat-chip{background:rgba(220,20,60,0.08);border:1px solid rgba(220,20,60,0.2);border-radius:10px;padding:8px 14px;text-align:center;min-width:80px;cursor:pointer;transition:all 0.2s;}')
lines.append('.stat-chip:hover{border-color:#dc143c;background:rgba(220,20,60,0.15);}')
lines.append('.stat-chip .num{font-size:18px;font-weight:700;}')
lines.append('.stat-chip .lbl{font-size:10px;color:#888;text-transform:uppercase;letter-spacing:1px;}')
lines.append('.detail-modal{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.88);z-index:9999;justify-content:center;align-items:center;}')
lines.append('.detail-box{background:linear-gradient(135deg,#1a1a1a,#2a2a2a);border:2px solid #dc143c;border-radius:18px;padding:30px;max-width:560px;width:92%;max-height:85vh;overflow-y:auto;position:relative;box-shadow:0 20px 60px rgba(220,20,60,0.4);}')
lines.append('.detail-row{display:flex;gap:10px;margin-ботtom:12px;align-items:flex-start;}')
lines.append('.detail-label{color:#888;font-size:11px;text-transform:uppercase;letter-spacing:1px;min-width:110px;flex-shrink:0;padding-top:2px;}')
lines.append('.detail-value{color:#eee;font-size:13px;flex:1;word-break:break-word;}')
lines.append('.msg-box{background:#0a0a0a;border:1px solid rgba(220,20,60,0.2);border-radius:8px;padding:12px;color:#ccc;font-size:13px;line-height:1.5;white-space:pre-wrap;word-break:break-word;}')
lines.append('.msg-box.deleted{border-color:rgba(231,76,60,0.4);background:rgba(231,76,60,0.05);}')
lines.append('.msg-box.edited-before{border-color:rgba(243,156,18,0.3);background:rgba(243,156,18,0.03);}')
lines.append('.msg-box.edited-after{border-color:rgba(46,204,113,0.3);background:rgba(46,204,113,0.03);}')
lines.append('</style>')
lines.append('')
lines.append('<div class="stats-bar" id="stats-bar"></div>')
lines.append('<div class="section">')
lines.append('  <div class="filter-bar">')
lines.append('    <input type="text" id="search" placeholder="Kullanici, channel, message ara..." oninput="applyFilters()">')
lines.append('    <select id="guild-filter" onchange="applyFilters()"><option value="">Tum Серверlar</option></select>')
lines.append('  </div>')
lines.append('  <div class="filter-bar" id="cat-buttons" style="margin-ботtom:15px;"></div>')
lines.append('  <div id="event-list" style="display:flex;flex-direction:column;gap:5px;"><div style="text-align:center;padding:50px;color:#555;"><i class="fas fa-spinner fa-spin" style="font-size:28px;color:#dc143c;"></i><br><br>Yukleniyor...</div></div>')
lines.append('  <div id="load-more-wrap" style="text-align:center;margin-top:15px;display:none;">')
lines.append('    <button id="load-more-btn" style="background:rgba(220,20,60,0.15);border:2px solid rgba(220,20,60,0.4);color:#dc143c;padding:9px 28px;border-radius:8px;cursor:pointer;font-size:13px;">Daha Fazla Yukle</button>')
lines.append('  </div>')
lines.append('</div>')
lines.append('')
lines.append('<div id="detailModal" class="detail-modal">')
lines.append('  <div class="detail-box">')
lines.append('    <button id="closeDetail" style="position:absolute;top:12px;right:16px;background:none;border:none;color:#dc143c;font-size:24px;cursor:pointer;">&times;</button>')
lines.append('    <div id="detailContent"></div>')
lines.append('  </div>')
lines.append('</div>')
lines.append('')
lines.append('<script>')
lines.append('var allEvents=[], filtered=[], currentCat="", shown=0, PAGE=100;')
lines.append('')
lines.append('var CATS={')
lines.append('  mod:    {icon:"🔨",label:"Mod",    bg:"rgba(231,76,60,0.2)", border:"rgba(231,76,60,0.5)", text:"#e74c3c"},')
lines.append('  member: {icon:"👤",label:"Uye",    bg:"rgba(46,204,113,0.2)",border:"rgba(46,204,113,0.5)",text:"#2ecc71"},')
lines.append('  message:{icon:"💬",label:"Сообщение",  bg:"rgba(52,152,219,0.2)",border:"rgba(52,152,219,0.5)",text:"#3498db"},')
lines.append('  role:   {icon:"🎭",label:"Роль",    bg:"rgba(155,89,182,0.2)",border:"rgba(155,89,182,0.5)",text:"#9b59b6"},')
lines.append('  channel:{icon:"📺",label:"Канал",  bg:"rgba(243,156,18,0.2)",border:"rgba(243,156,18,0.5)",text:"#f39c12"},')
lines.append('  voice:  {icon:"🔊",label:"Голос",    bg:"rgba(26,188,156,0.2)",border:"rgba(26,188,156,0.5)",text:"#1abc9c"},')
lines.append('  server: {icon:"🏰",label:"Сервер", bg:"rgba(230,126,34,0.2)",border:"rgba(230,126,34,0.5)",text:"#e67e22"},')
lines.append('  automod:{icon:"🤖",label:"AutoMod",bg:"rgba(231,76,60,0.2)", border:"rgba(231,76,60,0.5)", text:"#e74c3c"},')
lines.append('  invite: {icon:"📨",label:"Davet",  bg:"rgba(149,165,166,0.2)",border:"rgba(149,165,166,0.5)",text:"#95a5a6"}')
lines.append('};')
lines.append('')
lines.append('function buildCatButtons(){')
lines.append('  var w=document.getElementById("cat-buttons");')
lines.append('  var h="<button class=\\"cat-btn active\\" data-cat=\\"\\">Tumu</button> ";')
lines.append('  Object.keys(CATS).forEach(function(k){h+="<button class=\\"cat-btn\\" data-cat=\\""+k+"\\">"+CATS[k].icon+" "+CATS[k].label+"</button> ";});')
lines.append('  w.innerHTML=h;')
lines.append('  w.querySelectorAll(".cat-btn").forEach(function(b){')
lines.append('    b.addEventListener("click",function(){')
lines.append('      w.querySelectorAll(".cat-btn").forEach(function(x){x.classList.remove("active");});')
lines.append('      this.classList.add("active");')
lines.append('      currentCat=this.getAttribute("data-cat");')
lines.append('      applyFilters();')
lines.append('    });')
lines.append('  });')
lines.append('}')
lines.append('')
lines.append('function shortDetail(ev){')
lines.append('  var p=[];')
lines.append('  if(ev.user_name) p.push("<span style=\\"color:#dc143c;\\">@"+ev.user_name+"</span>");')
lines.append('  if(ev.channel) p.push("<span style=\\"color:#3498db;\\">#"+ev.channel+"</span>");')
lines.append('  if(ev.content) p.push("<span style=\\"color:#666;\\">"+String(ev.content).substring(0,60)+(ev.content.length>60?"...":"")+"</span>");')
lines.append('  if(ev.before) p.push("<span style=\\"color:#666;\\">"+String(ev.before).substring(0,50)+"...</span>");')
lines.append('  if(ev.old_name&&ev.new_name) p.push(ev.old_name+" → <b style=\\"color:white;\\">"+ev.new_name+"</b>");')
lines.append('  if(ev.added_roles&&ev.added_roles.length) p.push("➕ "+ev.added_roles.join(", "));')
lines.append('  if(ev.removed_roles&&ev.removed_roles.length) p.push("➖ "+ev.removed_roles.join(", "));')
lines.append('  if(ev.reason) p.push("<span style=\\"color:#f39c12;\\">"+String(ev.reason).substring(0,60)+"</span>");')
lines.append('  if(ev.code) p.push("discord.gg/"+ev.code);')
lines.append('  return p.join(" · ") || "<span style=\\"color:#333;\\">-</span>";')
lines.append('}')
lines.append('')
lines.append('function formatTime(ts){')
lines.append('  if(!ts) return "-";')
lines.append('  var d=new Date(ts), diff=Math.floor((Date.now()-d)/1000);')
lines.append('  if(diff<60) return diff+"s once";')
lines.append('  if(diff<3600) return Math.floor(diff/60)+"dk once";')
lines.append('  if(diff<86400) return Math.floor(diff/3600)+"sa once";')
lines.append('  return d.toLocaleDateString("tr-TR")+" "+d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});')
lines.append('}')
lines.append('')
lines.append('function fullTime(ts){')
lines.append('  if(!ts) return "-";')
lines.append('  var d=new Date(ts);')
lines.append('  return d.toLocaleDateString("tr-TR",{weekday:"long",year:"numeric",month:"long",day:"numeric"})+" "+d.toLocaleTimeString("tr-TR");')
lines.append('}')
lines.append('')
lines.append('function renderEvents(){')
lines.append('  var list=document.getElementById("event-list");')
lines.append('  var lmw=document.getElementById("load-more-wrap");')
lines.append('  if(!filtered.length){')
lines.append('    list.innerHTML="<div style=\\"text-align:center;padding:50px;color:#555;\\"><i class=\\"fas fa-search\\" style=\\"font-size:32px;\\"></i><br><br>Последнийuc bulunamadi</div>";')
lines.append('    lmw.style.display="none"; return;')
lines.append('  }')
lines.append('  var slice=filtered.slice(0,shown), html="";')
lines.append('  for(var i=0;i<slice.length;i++){')
lines.append('    var ev=slice[i], cat=ev.category||"mod", c=CATS[cat]||CATS.mod;')
lines.append('    html+="<div class=\\"ev-row\\">";')
lines.append('    html+="<div class=\\"ev-icon\\">"+c.icon+"</div>";')
lines.append('    html+="<div class=\\"ev-cat\\" style=\\"background:"+c.bg+";border:1px solid "+c.border+";color:"+c.text+"\\">"+c.label+"</div>";')
lines.append('    html+="<div class=\\"ev-action\\">"+(ev.action||"-")+"</div>";')
lines.append('    html+="<div class=\\"ev-detail\\">"+shortDetail(ev)+"</div>";')
lines.append('    html+="<div class=\\"ev-time\\">"+formatTime(ev.timestamp)+"</div>";')
lines.append('    html+="<button class=\\"ev-btn\\" data-idx=\\""+filtered.indexOf(ev)+"\\">Detay</button>";')
lines.append('    html+="</div>";')
lines.append('  }')
lines.append('  list.innerHTML=html;')
lines.append('  list.querySelectorAll(".ev-btn").forEach(function(btn){')
lines.append('    btn.addEventListener("click",function(){showDetail(parseInt(this.getAttribute("data-idx")));});')
lines.append('  });')
lines.append('  lmw.style.display=shown<filtered.length?"block":"none";')
lines.append('}')
lines.append('')
lines.append('function showDetail(idx){')
lines.append('  var ev=filtered[idx];')
lines.append('  if(!ev) return;')
lines.append('  var cat=ev.category||"mod", c=CATS[cat]||CATS.mod;')
lines.append('  var h="";')
lines.append('  h+="<div style=\\"display:flex;align-items:center;gap:12px;margin-ботtom:20px;padding-ботtom:15px;border-ботtom:1px solid rgba(220,20,60,0.2);\\">";')
lines.append('  h+="<span style=\\"font-size:32px;\\">"+c.icon+"</span>";')
lines.append('  h+="<div><div style=\\"color:#dc143c;font-size:18px;font-weight:700;\\">"+(ev.action||"-")+"</div>";')
lines.append('  h+="<div style=\\"color:#888;font-size:12px;\\">"+c.label+" · "+fullTime(ev.timestamp)+"</div></div></div>";')
lines.append('  function row(label,val){')
lines.append('    if(!val&&val!==0) return "";')
lines.append('    return "<div class=\\"detail-row\\"><div class=\\"detail-label\\">"+label+"</div><div class=\\"detail-value\\">"+val+"</div></div>";')
lines.append('  }')
lines.append('  if(ev.user_name) h+=row("Kullanici","<span style=\\"color:#dc143c;font-weight:700;\\">@"+ev.user_name+"</span>");')
lines.append('  if(ev.user_id) h+=row("Kullanici ID","<code style=\\"color:#aaa;font-size:12px;\\">"+ev.user_id+"</code>");')
lines.append('  if(ev.channel) h+=row("Канал","<span style=\\"color:#3498db;\\">#"+ev.channel+"</span>");')
lines.append('  if(ev.channel_id) h+=row("Канал ID","<code style=\\"color:#aaa;font-size:12px;\\">"+ev.channel_id+"</code>");')
lines.append('  if(ev.guild_id) h+=row("Сервер ID","<code style=\\"color:#aaa;font-size:12px;\\">"+ev.guild_id+"</code>");')
lines.append('  if(ev.mod_id) h+=row("Moderator ID","<code style=\\"color:#aaa;font-size:12px;\\">"+ev.mod_id+"</code>");')
lines.append('  if(ev.reason) h+=row("Причина","<span style=\\"color:#f39c12;\\">"+ev.reason+"</span>");')
lines.append('  if(ev.message_id) h+=row("Сообщение ID","<code style=\\"color:#aaa;font-size:12px;\\">"+ev.message_id+"</code>");')
lines.append('  if(ev.account_age_days!==undefined) h+=row("Hesap Yasi",ev.account_age_days+" gun");')
lines.append('  if(ev.roles&&ev.roles.length) h+=row("Рольler",ev.roles.join(", "));')
lines.append('  if(ev.added_roles&&ev.added_roles.length) h+=row("Добавитьnen Рольler","<span style=\\"color:#2ecc71;\\">"+ev.added_roles.join(", ")+"</span>");')
lines.append('  if(ev.removed_roles&&ev.removed_roles.length) h+=row("Kaldirilan Рольler","<span style=\\"color:#e74c3c;\\">"+ev.removed_roles.join(", ")+"</span>");')
lines.append('  if(ev.old_name) h+=row("Старый Имя","<span style=\\"color:#e74c3c;\\">"+ev.old_name+"</span>");')
lines.append('  if(ev.new_name) h+=row("Новый Имя","<span style=\\"color:#2ecc71;\\">"+ev.new_name+"</span>");')
lines.append('  if(ev.old_nick) h+=row("Старый Nick","<span style=\\"color:#e74c3c;\\">"+ev.old_nick+"</span>");')
lines.append('  if(ev.new_nick) h+=row("Новый Nick","<span style=\\"color:#2ecc71;\\">"+ev.new_nick+"</span>");')
lines.append('  if(ev.max_uses) h+=row("Maks Kullanim",ev.max_uses);')
lines.append('  if(ev.code) h+=row("Davet Kodu","discord.gg/"+ev.code);')
lines.append('  // Сообщение icerikleri')
lines.append('  if(ev.content&&ev.action==="Сообщение Yazildi") h+="<div style=\\"margin-top:15px;\\"><div style=\\"color:#888;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin-ботtom:6px;\\">Сообщение Icerigi</div><div class=\\"msg-box\\">"+ev.content+"</div></div>";')
lines.append('  if(ev.content&&ev.action==="Сообщение Удалено") h+="<div style=\\"margin-top:15px;\\"><div style=\\"color:#e74c3c;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin-ботtom:6px;\\">🗑️ Удалитьinen Сообщение</div><div class=\\"msg-box deleted\\">"+ev.content+"</div></div>";')
lines.append('  if(ev.before) h+="<div style=\\"margin-top:15px;\\"><div style=\\"color:#f39c12;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin-ботtom:6px;\\">✏️ Onceki Сообщение</div><div class=\\"msg-box edited-before\\">"+ev.before+"</div></div>";')
lines.append('  if(ev.after) h+="<div style=\\"margin-top:8px;\\"><div style=\\"color:#2ecc71;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin-ботtom:6px;\\">✅ Новый Сообщение</div><div class=\\"msg-box edited-after\\">"+ev.after+"</div></div>";')
lines.append('  document.getElementById("detailContent").innerHTML=h;')
lines.append('  document.getElementById("detailModal").style.display="flex";')
lines.append('}')
lines.append('')
lines.append('function applyFilters(){')
lines.append('  var q=document.getElementById("search").value.toLowerCase();')
lines.append('  var gid=document.getElementById("guild-filter").value;')
lines.append('  filtered=allEvents.filter(function(ev){')
lines.append('    if(currentCat&&ev.category!==currentCat) return false;')
lines.append('    if(gid&&ev.guild_id!==gid) return false;')
lines.append('    if(q&&!JSON.stringify(ev).toLowerCase().includes(q)) return false;')
lines.append('    return true;')
lines.append('  });')
lines.append('  shown=PAGE; renderEvents(); buildStats();')
lines.append('}')
lines.append('')
lines.append('function buildStats(){')
lines.append('  var counts={};')
lines.append('  allEvents.forEach(function(ev){var c=ev.category||"mod";counts[c]=(counts[c]||0)+1;});')
lines.append('  var h="<div class=\\"stat-chip\\" data-cat=\\"\\"><div class=\\"num\\" style=\\"color:#dc143c;\\">"+allEvents.length+"</div><div class=\\"lbl\\">Всего</div></div>";')
lines.append('  Object.keys(CATS).forEach(function(k){')
lines.append('    if(!counts[k]) return;')
lines.append('    var c=CATS[k];')
lines.append('    h+="<div class=\\"stat-chip\\" data-cat=\\""+k+"\\" style=\\"border-color:"+c.border+";\\"><div class=\\"num\\" style=\\"color:"+c.text+"\\">"+counts[k]+"</div><div class=\\"lbl\\">"+c.icon+" "+c.label+"</div></div>";')
lines.append('  });')
lines.append('  var bar=document.getElementById("stats-bar");')
lines.append('  bar.innerHTML=h;')
lines.append('  bar.querySelectorAll(".stat-chip").forEach(function(chip){')
lines.append('    chip.addEventListener("click",function(){')
lines.append('      var cat=this.getAttribute("data-cat");')
lines.append('      var btn=document.querySelector(".cat-btn[data-cat=\\""+cat+"\\"]");')
lines.append('      if(btn) btn.click();')
lines.append('    });')
lines.append('  });')
lines.append('}')
lines.append('')
lines.append('function populateGuilds(){')
lines.append('  var guilds={};')
lines.append('  allEvents.forEach(function(ev){if(ev.guild_id) guilds[ev.guild_id]=true;});')
lines.append('  var sel=document.getElementById("guild-filter");')
lines.append('  sel.innerHTML="<option value=\\"\\">Tum Серверlar</option>";')
lines.append('  Object.keys(guilds).forEach(function(gid){sel.innerHTML+="<option value=\\""+gid+"\\">"+gid+"</option>";});')
lines.append('}')
lines.append('')
lines.append('document.getElementById("load-more-btn").addEventListener("click",function(){shown+=PAGE;renderEvents();});')
lines.append('document.getElementById("closeDetail").addEventListener("click",function(){document.getElementById("detailModal").style.display="none";});')
lines.append('document.getElementById("detailModal").addEventListener("click",function(e){if(e.target===this) this.style.display="none";});')
lines.append('')
lines.append('async function loadLogs(){')
lines.append('  try{')
lines.append('    var r=await fetch("/api/logs");')
lines.append('    allEvents=await r.json();')
lines.append('    populateGuilds(); applyFilters();')
lines.append('  }catch(e){')
lines.append('    document.getElementById("event-list").innerHTML="<p style=\\"color:#e74c3c;text-align:center;padding:40px;\\">Ошибка: "+e.message+"</p>";')
lines.append('  }')
lines.append('}')
lines.append('')
lines.append('buildCatButtons(); loadLogs(); setInterval(loadLogs,15000);')
lines.append('</script>')
lines.append('{% endblock %}')

content = '\n'.join(lines)
with open(os.path.join(templates_dir, 'logs.html'), 'w', encoding='utf-8') as f:
    f.write(content)
print("logs.html записатьildi - " + str(len(lines)) + " satir")
